postgresql:
  global:
    postgresql:
      auth:
        # username: utku
        # password: utku
        enablePostgresUser: true
        postgresPassword: postgres
        database: initial

  primary:
    service:
      type: LoadBalancer
    nodeSelector:
      kubernetes.io/hostname: worker-2
    initContainers:
      - name: create-tablespace-folders
        image: busybox:latest
        command: 
          - sh
          - -c
        args:
          - |
            mkdir -p /tablespaces/happiness && \
            mkdir -p /tablespaces/inflation && \
            chown -R 1001:0 /tablespaces && \
            ls -al /tablespaces
        volumeMounts:
          - name: tablespaces
            mountPath: /tablespaces
    extraVolumeMounts:
      - name: migrations
        mountPath: /migrations
        readOnly: true
      - name: user-data
        mountPath: /user-data
        readOnly: true
      - name: tablespaces
        mountPath: /tablespaces
      - name: dumps
        mountPath: /dumps
    extraVolumes:
      - name: dumps
        hostPath:
          path: /dumps
          type: DirectoryOrCreate
      - name: migrations
        hostPath:
          path: /migrations
          type: DirectoryOrCreate
      - name: user-data
        hostPath:
          path: /user-data
          type: DirectoryOrCreate
      - name: tablespaces
        hostPath:
          path: /var/lib/rancher/k3s/storage/tablespaces
          type: DirectoryOrCreate
    initdb:
      scripts:
        migrate-raw-data.sh: |
          PGPASSWORD=postgres \
            psql -U postgres -d initial -c "\i /migrations/init.sql"
        # migrate-from-dumps.sh: |
        #   cat /dumps/all.gz | gunzip | PGPASSWORD=postgres psql -U postgres
          
